### ISSUE TITLE
permettre la destruction des buildings

### ISSUE THREAD

**Issue by Hatscat** [solfen/Doge_Tycoon#3]

**Comment by solfen** [comment]
Ne fonctione pas.
Le code passe bien dans Building.destroy et dans IsoMap.destroy_building mais le batiment n'est pas suprimé.
J'ai mis des trace() pour être sûr.

**Comment by solfen** [comment]
Erreur quand on détruit un batiment. Une fois le batiment détruit, chaque clic n'importe ou sur l'écran appelra la méthode _click de l'objet
